BEGIN TRANSACTION;
CREATE TABLE asesor_tienda (
        usuario_id INTEGER,
        tienda_id INTEGER,
        FOREIGN KEY(usuario_id) REFERENCES usuarios(id),
        FOREIGN KEY(tienda_id) REFERENCES tiendas(id),
        PRIMARY KEY(usuario_id, tienda_id)
    );
CREATE TABLE retiros (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        numero_retiro TEXT NOT NULL,
        tienda_cr TEXT NOT NULL,
        monto REAL NOT NULL,
        notas TEXT,
        imagen_fajilla TEXT,
        usuario_registro TEXT NOT NULL,
        usuario_confirma TEXT NOT NULL,
        fecha TEXT NOT NULL,
        hora TEXT NOT NULL,
        fecha_hora_registro TEXT NOT NULL
    );
CREATE TABLE tiendas (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        cr TEXT UNIQUE NOT NULL,
        nombre TEXT NOT NULL,
        distrito TEXT
    );
INSERT INTO "tiendas" VALUES(1,'505YL','Crucero Sendero MAF',NULL);
INSERT INTO "tiendas" VALUES(2,'506ZG','Nuevo Milenio MAF',NULL);
INSERT INTO "tiendas" VALUES(4,'509CO','Porfirio Diaz MAF',NULL);
INSERT INTO "tiendas" VALUES(6,'509T4','Paseo de la Castellana MAF',NULL);
INSERT INTO "tiendas" VALUES(7,'5008G','Palmillas MAF',NULL);
INSERT INTO "tiendas" VALUES(9,'500D5','22 Mina MAF',NULL);
INSERT INTO "tiendas" VALUES(14,'50ACI','Acuario MAF',NULL);
INSERT INTO "tiendas" VALUES(15,'500N0','Relaciones Exteriores MAF',NULL);
INSERT INTO "tiendas" VALUES(16,'50AZP','Realdelas Palmas MAF',NULL);
INSERT INTO "tiendas" VALUES(21,'5012S','Cultural TAM',NULL);
INSERT INTO "tiendas" VALUES(22,'50B9K','Portillo MAF',NULL);
INSERT INTO "tiendas" VALUES(23,'50181','Camaleon TAM',NULL);
INSERT INTO "tiendas" VALUES(24,'50COW','Constituyentes MAF',NULL);
INSERT INTO "tiendas" VALUES(25,'50CSA','Casa Blanca MAF',NULL);
INSERT INTO "tiendas" VALUES(27,'501EA','Baez MAF',NULL);
INSERT INTO "tiendas" VALUES(29,'501HK','SANTA ELENA',NULL);
INSERT INTO "tiendas" VALUES(31,'501LU','Sierra Morena TAM',NULL);
INSERT INTO "tiendas" VALUES(32,'501O5','La Perla MAF',NULL);
INSERT INTO "tiendas" VALUES(33,'501SI','Alfa MAF',NULL);
INSERT INTO "tiendas" VALUES(34,'50F3Z','Rigo Tovar MAF',NULL);
INSERT INTO "tiendas" VALUES(35,'50G9W','Palmares Norte MAF',NULL);
INSERT INTO "tiendas" VALUES(37,'501XB','Martires MAF',NULL);
INSERT INTO "tiendas" VALUES(38,'50II4','Villa Española MAF',NULL);
INSERT INTO "tiendas" VALUES(39,'501XQ','Vialidad PD TAM',NULL);
INSERT INTO "tiendas" VALUES(41,'5023U','Reforma TAM',NULL);
INSERT INTO "tiendas" VALUES(42,'50J3M','Tianguis Palmares MAF',NULL);
INSERT INTO "tiendas" VALUES(43,'5025Q','Royal Country MAF',NULL);
INSERT INTO "tiendas" VALUES(45,'5029T','Gas Altamira TAM',NULL);
INSERT INTO "tiendas" VALUES(48,'50LXF','Leyes de Reforma MAF',NULL);
INSERT INTO "tiendas" VALUES(49,'502CG','31 Berriozabal MAF',NULL);
INSERT INTO "tiendas" VALUES(51,'50MFU','Magisterio MAF',NULL);
INSERT INTO "tiendas" VALUES(53,'502K2','Jaumave Plaza MAF',NULL);
INSERT INTO "tiendas" VALUES(54,'502MB','Burgos TAM',NULL);
INSERT INTO "tiendas" VALUES(55,'502O6','Colinas TAM',NULL);
INSERT INTO "tiendas" VALUES(56,'502R0','C-5 MAF',NULL);
INSERT INTO "tiendas" VALUES(58,'502UP','San Antonio TAM',NULL);
INSERT INTO "tiendas" VALUES(59,'502YC','NICOLAS BRAVO TAM',NULL);
INSERT INTO "tiendas" VALUES(61,'5038G','Campbell TAM',NULL);
INSERT INTO "tiendas" VALUES(63,'503CP','Sulaiman MAF',NULL);
INSERT INTO "tiendas" VALUES(64,'50MSI','Santa Anita MAF',NULL);
INSERT INTO "tiendas" VALUES(65,'503DX','Encinos TAM',NULL);
INSERT INTO "tiendas" VALUES(66,'503HL','Hydros TAM',NULL);
INSERT INTO "tiendas" VALUES(68,'50MYV','12 de Marzo MAF',NULL);
INSERT INTO "tiendas" VALUES(69,'503OF','Tres Marias MAF',NULL);
INSERT INTO "tiendas" VALUES(70,'503OG','Barquito TAM',NULL);
INSERT INTO "tiendas" VALUES(71,'503RS','Plaza Dorada MAF',NULL);
INSERT INTO "tiendas" VALUES(72,'503SN','Boulevard Echeverria MAF',NULL);
INSERT INTO "tiendas" VALUES(73,'503X5','El Campanario MAF',NULL);
INSERT INTO "tiendas" VALUES(74,'50NE6','Paseo de los Palmares MAF',NULL);
INSERT INTO "tiendas" VALUES(75,'50401','Revolucion Verde MAF',NULL);
INSERT INTO "tiendas" VALUES(76,'50OEG','Egipto MAF',NULL);
INSERT INTO "tiendas" VALUES(77,'504AD','Marina Centro',NULL);
INSERT INTO "tiendas" VALUES(78,'504EC','Bujanos TAM',NULL);
INSERT INTO "tiendas" VALUES(79,'504KG','Las Chacas TAM',NULL);
INSERT INTO "tiendas" VALUES(80,'504VH','Malitzin MAF',NULL);
INSERT INTO "tiendas" VALUES(81,'504W9','Moroncito TAM',NULL);
INSERT INTO "tiendas" VALUES(82,'504XP','Valle De Pajaritos MAF',NULL);
INSERT INTO "tiendas" VALUES(83,'50QEN','Quinta Real MAF',NULL);
INSERT INTO "tiendas" VALUES(84,'5055S','Calzada Blanca MAF',NULL);
INSERT INTO "tiendas" VALUES(85,'5058M','Alvaro TAM',NULL);
INSERT INTO "tiendas" VALUES(86,'505C7','Sierra Gorda MAF',NULL);
INSERT INTO "tiendas" VALUES(87,'505CO','Ejido La Pesca MAF',NULL);
INSERT INTO "tiendas" VALUES(88,'505CV','Hombres Ilustres 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(89,'50SFW','San Felipe MAF',NULL);
INSERT INTO "tiendas" VALUES(90,'505ER','Torres Norte TAM',NULL);
INSERT INTO "tiendas" VALUES(91,'505EV','Gonzalitos MAF',NULL);
INSERT INTO "tiendas" VALUES(93,'50UJD','Industrial MAF',NULL);
INSERT INTO "tiendas" VALUES(94,'505MH','Lagunas de Miralta TAM',NULL);
INSERT INTO "tiendas" VALUES(95,'505MR','Colegio Militar TAM',NULL);
INSERT INTO "tiendas" VALUES(96,'505P0','Mercado Madero TAM',NULL);
INSERT INTO "tiendas" VALUES(97,'505Q5','Río Tamesí MAF',NULL);
INSERT INTO "tiendas" VALUES(98,'50URF','San Rafael MAF',NULL);
INSERT INTO "tiendas" VALUES(99,'50VWR','Valle Real MAF',NULL);
INSERT INTO "tiendas" VALUES(101,'505XR','Chairel TAM',NULL);
INSERT INTO "tiendas" VALUES(102,'505Y9','Corredor Urbano TAM',NULL);
INSERT INTO "tiendas" VALUES(103,'50ZDK','Quinta Real 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(104,'5060E','PEDRO SOSA 1 MAF',NULL);
INSERT INTO "tiendas" VALUES(105,'50639','El Jardin MAF',NULL);
INSERT INTO "tiendas" VALUES(106,'5064O','El Maderense MAF',NULL);
INSERT INTO "tiendas" VALUES(107,'5065F','La Estrella MAF',NULL);
INSERT INTO "tiendas" VALUES(110,'506AR','El Barretal MAF',NULL);
INSERT INTO "tiendas" VALUES(111,'50060','Delphi MAF',NULL);
INSERT INTO "tiendas" VALUES(112,'503X6','Inteva Alianza MAF',NULL);
INSERT INTO "tiendas" VALUES(114,'50423','El Caracol MAF',NULL);
INSERT INTO "tiendas" VALUES(115,'506IK','Valle Dorado TAM',NULL);
INSERT INTO "tiendas" VALUES(117,'506L1','Santa Fe TAM',NULL);
INSERT INTO "tiendas" VALUES(119,'506NE','Centenario MAF',NULL);
INSERT INTO "tiendas" VALUES(120,'506OI','Vista Bella MAF',NULL);
INSERT INTO "tiendas" VALUES(121,'506QT','Matienzo TAM',NULL);
INSERT INTO "tiendas" VALUES(122,'506RG','Llera Centro TAM',NULL);
INSERT INTO "tiendas" VALUES(123,'506S5','La Tamaulipeca MAF',NULL);
INSERT INTO "tiendas" VALUES(124,'505UA','Las Rusias MAF',NULL);
INSERT INTO "tiendas" VALUES(126,'50A35','Santa Maria MAF',NULL);
INSERT INTO "tiendas" VALUES(128,'5071I','Isauro Alfaro TAM',NULL);
INSERT INTO "tiendas" VALUES(129,'5072E','Sonora TAM',NULL);
INSERT INTO "tiendas" VALUES(130,'5072G','Victoria TAM',NULL);
INSERT INTO "tiendas" VALUES(132,'5074G','De Los Rios TAM',NULL);
INSERT INTO "tiendas" VALUES(134,'507EU','Rio Blanco MAF',NULL);
INSERT INTO "tiendas" VALUES(135,'507HY','El Navegante MAF',NULL);
INSERT INTO "tiendas" VALUES(136,'507IG','Espejo MAF',NULL);
INSERT INTO "tiendas" VALUES(137,'507JI','Nuevo Santander UMI',NULL);
INSERT INTO "tiendas" VALUES(138,'507KD','Plaza Altavista MAF',NULL);
INSERT INTO "tiendas" VALUES(140,'507OV','Villas del Sol TAM',NULL);
INSERT INTO "tiendas" VALUES(141,'507Q4','Teosuchil MAF',NULL);
INSERT INTO "tiendas" VALUES(143,'507SX','Monte Alto UMI',NULL);
INSERT INTO "tiendas" VALUES(144,'50BBH','Villa del Parque MAM',NULL);
INSERT INTO "tiendas" VALUES(145,'507VU','Petrolera TAM',NULL);
INSERT INTO "tiendas" VALUES(146,'50BIY','Ejido los Arados MAM',NULL);
INSERT INTO "tiendas" VALUES(147,'50BNK','Lucio Blanco II MAF',NULL);
INSERT INTO "tiendas" VALUES(149,'5081E','Esteros TAM',NULL);
INSERT INTO "tiendas" VALUES(151,'50839','Grecia MAF',NULL);
INSERT INTO "tiendas" VALUES(154,'5085F','Tamaulipas II TAM',NULL);
INSERT INTO "tiendas" VALUES(155,'50893','Petroquimicas TAM',NULL);
INSERT INTO "tiendas" VALUES(157,'508CF','Pakistan TAM',NULL);
INSERT INTO "tiendas" VALUES(158,'508DH','Vicente Guerrero MAF',NULL);
INSERT INTO "tiendas" VALUES(159,'50BYS','Las Brisas MAF',NULL);
INSERT INTO "tiendas" VALUES(160,'508FV','Coplamar MAF',NULL);
INSERT INTO "tiendas" VALUES(161,'508HH','Clínica IMSS MAF',NULL);
INSERT INTO "tiendas" VALUES(163,'508OK','El Dorado MAF',NULL);
INSERT INTO "tiendas" VALUES(164,'50DEW','Sendero III MAF',NULL);
INSERT INTO "tiendas" VALUES(165,'508R4','Jimenez TAM',NULL);
INSERT INTO "tiendas" VALUES(166,'508SU','Canarios TAM',NULL);
INSERT INTO "tiendas" VALUES(167,'508UF','33 Juarez MAF',NULL);
INSERT INTO "tiendas" VALUES(171,'50956','Luis Caballero TAM',NULL);
INSERT INTO "tiendas" VALUES(173,'5096D','Electricistas TAM',NULL);
INSERT INTO "tiendas" VALUES(174,'50973','Sector 3 TAM',NULL);
INSERT INTO "tiendas" VALUES(175,'5097Z','Marte MAF',NULL);
INSERT INTO "tiendas" VALUES(177,'509AD','Del Norte MAF',NULL);
INSERT INTO "tiendas" VALUES(178,'509BC','Victoria Centro MAF',NULL);
INSERT INTO "tiendas" VALUES(179,'50EBA','El Ebanito MAF',NULL);
INSERT INTO "tiendas" VALUES(181,'509KX','Gas El 40 TMP',NULL);
INSERT INTO "tiendas" VALUES(183,'509SJ','Via Monterrey',NULL);
INSERT INTO "tiendas" VALUES(184,'50EKE','Del Valle MAF',NULL);
INSERT INTO "tiendas" VALUES(185,'509UI','Gas Monte Alto TAM',NULL);
INSERT INTO "tiendas" VALUES(188,'509YX','Aptiv MAF',NULL);
INSERT INTO "tiendas" VALUES(189,'50GGG','Brisas del Valle MAF',NULL);
INSERT INTO "tiendas" VALUES(190,'50IBF','Uniones MAF',NULL);
INSERT INTO "tiendas" VALUES(191,'50JZI','Las Brisas 3 MAF',NULL);
INSERT INTO "tiendas" VALUES(192,'50A5F','Talleres TAM',NULL);
INSERT INTO "tiendas" VALUES(194,'50A92','Zurita MAF',NULL);
INSERT INTO "tiendas" VALUES(195,'50QOO','Lucio Blanco MAF',NULL);
INSERT INTO "tiendas" VALUES(196,'50ABO','Arboledas TAM',NULL);
INSERT INTO "tiendas" VALUES(197,'50SFY','Sendero II MAF',NULL);
INSERT INTO "tiendas" VALUES(198,'50AER','Las Americas TAM',NULL);
INSERT INTO "tiendas" VALUES(199,'50AET','Aeropuerto TAM',NULL);
INSERT INTO "tiendas" VALUES(200,'50AEV','Maeva TAM',NULL);
INSERT INTO "tiendas" VALUES(205,'50AGW','Agua Dulce TAM',NULL);
INSERT INTO "tiendas" VALUES(206,'50AIC','Revolucion Verde TAM',NULL);
INSERT INTO "tiendas" VALUES(207,'50SYN','Sendero I MAF',NULL);
INSERT INTO "tiendas" VALUES(208,'50AJH','Alameda TAM',NULL);
INSERT INTO "tiendas" VALUES(209,'50T77','Inteva MAF',NULL);
INSERT INTO "tiendas" VALUES(210,'50ALC','Alarcon TAM',NULL);
INSERT INTO "tiendas" VALUES(211,'50ALR','Altamira TAM',NULL);
INSERT INTO "tiendas" VALUES(212,'50AMH','Isleta TAM',NULL);
INSERT INTO "tiendas" VALUES(214,'50APC','Lirios TAM',NULL);
INSERT INTO "tiendas" VALUES(215,'50APH','IMSS TAM',NULL);
INSERT INTO "tiendas" VALUES(217,'50TBO','Tres Moras MAF',NULL);
INSERT INTO "tiendas" VALUES(219,'50ARO','Oro TAM',NULL);
INSERT INTO "tiendas" VALUES(221,'50ARV','Quintero TAM',NULL);
INSERT INTO "tiendas" VALUES(222,'50ASA','Tula TAM',NULL);
INSERT INTO "tiendas" VALUES(223,'50ASH','Asent. Humanos MAF',NULL);
INSERT INTO "tiendas" VALUES(224,'50AU4','Villa de Llera MAF',NULL);
INSERT INTO "tiendas" VALUES(225,'50AUN','Ampliacion TAM',NULL);
INSERT INTO "tiendas" VALUES(226,'50AV6','Valle Esmeralda TAM',NULL);
INSERT INTO "tiendas" VALUES(227,'50WKI','Los Presidentes MAF',NULL);
INSERT INTO "tiendas" VALUES(228,'50XFN','Las Brisas II MAF',NULL);
INSERT INTO "tiendas" VALUES(229,'50XLF','Las Fuentes MAF',NULL);
INSERT INTO "tiendas" VALUES(230,'50YHF','Empalme MAF',NULL);
INSERT INTO "tiendas" VALUES(231,'50AYN','Ayuntamiento TAM',NULL);
INSERT INTO "tiendas" VALUES(232,'5003W','Tercera MAF',NULL);
INSERT INTO "tiendas" VALUES(233,'5055Q','Benjamin Gaona MAF',NULL);
INSERT INTO "tiendas" VALUES(234,'506GX','Diego Rivera MAF',NULL);
INSERT INTO "tiendas" VALUES(235,'50B9S','Olivin MAF',NULL);
INSERT INTO "tiendas" VALUES(236,'50BAA','Refineria MAF',NULL);
INSERT INTO "tiendas" VALUES(237,'508DX','Electricistas MAF',NULL);
INSERT INTO "tiendas" VALUES(238,'50BAM','Nuevo Madero TAM',NULL);
INSERT INTO "tiendas" VALUES(239,'50BAX','Fco I. Madero TAM',NULL);
INSERT INTO "tiendas" VALUES(240,'50BBG','Cuartel MAF',NULL);
INSERT INTO "tiendas" VALUES(241,'50C4W','Aguas Subterraneas MAF',NULL);
INSERT INTO "tiendas" VALUES(242,'50BDK','San Luis TAM',NULL);
INSERT INTO "tiendas" VALUES(243,'50BDP','Azteca TAM',NULL);
INSERT INTO "tiendas" VALUES(246,'50BEH','Real del Mar TAM',NULL);
INSERT INTO "tiendas" VALUES(247,'50CAU','Curacao MAF',NULL);
INSERT INTO "tiendas" VALUES(248,'50GPL','Nicolas Guerra MAF',NULL);
INSERT INTO "tiendas" VALUES(249,'50BKE','Del Bosque TAM',NULL);
INSERT INTO "tiendas" VALUES(250,'50BMS','Colombia TAM',NULL);
INSERT INTO "tiendas" VALUES(252,'50II0','Jardines de San Juan MAF',NULL);
INSERT INTO "tiendas" VALUES(254,'50BRK','Laborcitas MAF',NULL);
INSERT INTO "tiendas" VALUES(255,'50BSX','Abasolo MAF',NULL);
INSERT INTO "tiendas" VALUES(256,'50BTC','Tolteca TAM',NULL);
INSERT INTO "tiendas" VALUES(257,'50BTM','BOLITAM TAM',NULL);
INSERT INTO "tiendas" VALUES(258,'50BXH','Deportivo Sur TAM',NULL);
INSERT INTO "tiendas" VALUES(259,'50BXI','Arenal TAM',NULL);
INSERT INTO "tiendas" VALUES(260,'50IUX','El Saucito MAM',NULL);
INSERT INTO "tiendas" VALUES(261,'50C2U','Valle del Sol MAF',NULL);
INSERT INTO "tiendas" VALUES(262,'50JD7','Expofiesta Oriente MAF',NULL);
INSERT INTO "tiendas" VALUES(263,'50C6M','Agronomos MAF',NULL);
INSERT INTO "tiendas" VALUES(266,'50C8A','Privanzas MAF',NULL);
INSERT INTO "tiendas" VALUES(267,'50JZD','Juarez II MAF',NULL);
INSERT INTO "tiendas" VALUES(268,'50CGZ','Gonzalez Centro TAM',NULL);
INSERT INTO "tiendas" VALUES(269,'50JZH','San Miguel MAF',NULL);
INSERT INTO "tiendas" VALUES(270,'50CHT','Cuauhtemoc TAM',NULL);
INSERT INTO "tiendas" VALUES(271,'50KJB','Satelite MAF',NULL);
INSERT INTO "tiendas" VALUES(272,'50CJN','Colon TAM',NULL);
INSERT INTO "tiendas" VALUES(274,'50CMP','Floresta TAM',NULL);
INSERT INTO "tiendas" VALUES(275,'50CMW','Civil Madero TAM',NULL);
INSERT INTO "tiendas" VALUES(276,'50LTR','Las Torres MAF',NULL);
INSERT INTO "tiendas" VALUES(277,'50CP6','Lara MAF',NULL);
INSERT INTO "tiendas" VALUES(278,'50CQ8','Club de Leones TAM',NULL);
INSERT INTO "tiendas" VALUES(279,'50MJN','San Juan MAF',NULL);
INSERT INTO "tiendas" VALUES(280,'50CRW','8 Carrera MAF',NULL);
INSERT INTO "tiendas" VALUES(281,'50NDN','Del Nino MAF',NULL);
INSERT INTO "tiendas" VALUES(282,'50CSB','FidelVelazquezII MAF',NULL);
INSERT INTO "tiendas" VALUES(283,'50CWO','Chapultepec TAM',NULL);
INSERT INTO "tiendas" VALUES(285,'50CYH','2 de Enero TAM',NULL);
INSERT INTO "tiendas" VALUES(286,'50CZK','Vidal TAM',NULL);
INSERT INTO "tiendas" VALUES(289,'50D60','Todos por Tamaulipas MAF',NULL);
INSERT INTO "tiendas" VALUES(290,'50D83','Olivin Centro MAF',NULL);
INSERT INTO "tiendas" VALUES(291,'50OSU','Suriname MAF',NULL);
INSERT INTO "tiendas" VALUES(292,'50D8L','Avenida Cuarta TAM',NULL);
INSERT INTO "tiendas" VALUES(293,'50SFN','San Fernando MAF',NULL);
INSERT INTO "tiendas" VALUES(294,'50D9A','Keppler MAF',NULL);
INSERT INTO "tiendas" VALUES(295,'50DAY','5 de Mayo TAM',NULL);
INSERT INTO "tiendas" VALUES(296,'50SJP','Solidaridad II MAF',NULL);
INSERT INTO "tiendas" VALUES(297,'50DCO','Crit TAM',NULL);
INSERT INTO "tiendas" VALUES(298,'50UBJ','Benito Juarez MAF',NULL);
INSERT INTO "tiendas" VALUES(299,'50DDL','Santa Anita TAM',NULL);
INSERT INTO "tiendas" VALUES(300,'50UML','Longoria MAF',NULL);
INSERT INTO "tiendas" VALUES(303,'50DM3','Gas Sunoco TAM',NULL);
INSERT INTO "tiendas" VALUES(304,'50DM5','Lindavista MAF',NULL);
INSERT INTO "tiendas" VALUES(305,'50DMW','Aldama II TAM',NULL);
INSERT INTO "tiendas" VALUES(306,'50UXJ','Lomas de San Juan MAF',NULL);
INSERT INTO "tiendas" VALUES(307,'50DNY','Germinal TAM',NULL);
INSERT INTO "tiendas" VALUES(308,'50DOQ','Pino TAM',NULL);
INSERT INTO "tiendas" VALUES(309,'50DPJ','Zeferino 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(310,'50DQC','14 Boulevard MAF',NULL);
INSERT INTO "tiendas" VALUES(311,'50VVN','20 Noviembre MAF',NULL);
INSERT INTO "tiendas" VALUES(312,'50DQF','22 Rosales MAF',NULL);
INSERT INTO "tiendas" VALUES(313,'50WPR','Tampico MAF',NULL);
INSERT INTO "tiendas" VALUES(314,'50Z8B','Tianguis del Niño MAF',NULL);
INSERT INTO "tiendas" VALUES(315,'50DQT','La Moderna MAF',NULL);
INSERT INTO "tiendas" VALUES(316,'50DQV','La Presita MAF',NULL);
INSERT INTO "tiendas" VALUES(317,'50ZMI','La Amistad MAF',NULL);
INSERT INTO "tiendas" VALUES(318,'50DQZ','Zeferino MAF',NULL);
INSERT INTO "tiendas" VALUES(321,'50DUI','Dona Cecilia TAM',NULL);
INSERT INTO "tiendas" VALUES(322,'50DVR','Divisoria TAM',NULL);
INSERT INTO "tiendas" VALUES(323,'50DWQ','Nuevo Padilla II MAF',NULL);
INSERT INTO "tiendas" VALUES(324,'50DY4','4 Boulevard MAF',NULL);
INSERT INTO "tiendas" VALUES(325,'5017X','Las Culturas MAF',NULL);
INSERT INTO "tiendas" VALUES(327,'50E20','Capitan TAM',NULL);
INSERT INTO "tiendas" VALUES(328,'50E2Q','Aviles MAF',NULL);
INSERT INTO "tiendas" VALUES(329,'50182','Guadalupe Mainero MAF',NULL);
INSERT INTO "tiendas" VALUES(330,'503JN','Vancouver MAF',NULL);
INSERT INTO "tiendas" VALUES(331,'50EDK','Carranza TAM',NULL);
INSERT INTO "tiendas" VALUES(336,'50EJE','Ejercito TAM',NULL);
INSERT INTO "tiendas" VALUES(337,'50EJN','Allende TAM',NULL);
INSERT INTO "tiendas" VALUES(338,'50AQ1','Mainero MAF',NULL);
INSERT INTO "tiendas" VALUES(339,'50ELO','Leones TAM',NULL);
INSERT INTO "tiendas" VALUES(340,'50EM0','Kehoe TAM',NULL);
INSERT INTO "tiendas" VALUES(341,'50ENP','Rio Verde TAM',NULL);
INSERT INTO "tiendas" VALUES(342,'50ENT','Centro TAM',NULL);
INSERT INTO "tiendas" VALUES(343,'50DCW','Canada MAF',NULL);
INSERT INTO "tiendas" VALUES(344,'50ESH','Est. Cuauhtemoc TAM',NULL);
INSERT INTO "tiendas" VALUES(345,'50ESN','Escandon TAM',NULL);
INSERT INTO "tiendas" VALUES(346,'50ESO','Estadio TAM',NULL);
INSERT INTO "tiendas" VALUES(347,'50ESC','Escandon MAF',NULL);
INSERT INTO "tiendas" VALUES(348,'50EUP','La Paz II MAF',NULL);
INSERT INTO "tiendas" VALUES(349,'50EUQ','Campestre del Lago MAF',NULL);
INSERT INTO "tiendas" VALUES(350,'50FIW','Finsa MAF',NULL);
INSERT INTO "tiendas" VALUES(353,'50EZL','Escolleras TAM',NULL);
INSERT INTO "tiendas" VALUES(354,'50F26','El Puerto MAF',NULL);
INSERT INTO "tiendas" VALUES(356,'50FUI','Fue. IndustrialesMAF',NULL);
INSERT INTO "tiendas" VALUES(357,'50GV9','Ciudad Industrial MAF',NULL);
INSERT INTO "tiendas" VALUES(358,'50IFX','Palmas de Mar MAF',NULL);
INSERT INTO "tiendas" VALUES(359,'50F4P','Fundo Legal MAF',NULL);
INSERT INTO "tiendas" VALUES(362,'50M7I','Parker MAF',NULL);
INSERT INTO "tiendas" VALUES(364,'50MHX','Camino Real MAF',NULL);
INSERT INTO "tiendas" VALUES(365,'50FDV','Fidel Velazquez MAF',NULL);
INSERT INTO "tiendas" VALUES(366,'50FE7','SANTA AMALIA',NULL);
INSERT INTO "tiendas" VALUES(367,'50FEG','Regional TAM',NULL);
INSERT INTO "tiendas" VALUES(368,'50FEY','Nacozary MAF',NULL);
INSERT INTO "tiendas" VALUES(369,'50FGM','Frente Democratico TAM',NULL);
INSERT INTO "tiendas" VALUES(370,'50FH3','Simon Bolivar MAF',NULL);
INSERT INTO "tiendas" VALUES(371,'50FIJ','Fraile TAM',NULL);
INSERT INTO "tiendas" VALUES(372,'50NU8','Fundadores MAF',NULL);
INSERT INTO "tiendas" VALUES(373,'50FMY','8 Boulevard MAF',NULL);
INSERT INTO "tiendas" VALUES(374,'50SJW','San Jeronimo 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(375,'50FV5','General San Martin MAF',NULL);
INSERT INTO "tiendas" VALUES(376,'50SJX','San Jeronimo MAF',NULL);
INSERT INTO "tiendas" VALUES(377,'50TEH','Teotihuacan MAF',NULL);
INSERT INTO "tiendas" VALUES(378,'50FYA','Arguelles MAF',NULL);
INSERT INTO "tiendas" VALUES(379,'50UOY','Playa MAF',NULL);
INSERT INTO "tiendas" VALUES(380,'50UPV','Palo Verde MAF',NULL);
INSERT INTO "tiendas" VALUES(382,'50GFO','Nacional MAF',NULL);
INSERT INTO "tiendas" VALUES(383,'50GFP','La Paz MAF',NULL);
INSERT INTO "tiendas" VALUES(386,'50XCI','La Cima MAF',NULL);
INSERT INTO "tiendas" VALUES(387,'50XGZ','Magnolias MAF',NULL);
INSERT INTO "tiendas" VALUES(388,'50GIC','Tecnologico TAM',NULL);
INSERT INTO "tiendas" VALUES(389,'50GKB','Ornato TAM',NULL);
INSERT INTO "tiendas" VALUES(390,'50GKT','Canseco TAM',NULL);
INSERT INTO "tiendas" VALUES(392,'50YDK','Longoreno MAF',NULL);
INSERT INTO "tiendas" VALUES(394,'50GRD','San Gerardo TAM',NULL);
INSERT INTO "tiendas" VALUES(395,'50GRF','Grafer TAM',NULL);
INSERT INTO "tiendas" VALUES(397,'50GTE','Guatemala TAM',NULL);
INSERT INTO "tiendas" VALUES(399,'50Z6S','Taxquena MAF',NULL);
INSERT INTO "tiendas" VALUES(400,'50GVI','Villahermosa TAM',NULL);
INSERT INTO "tiendas" VALUES(401,'50GZA','Zaragoza MAF',NULL);
INSERT INTO "tiendas" VALUES(402,'50GZK','Guemez MAF',NULL);
INSERT INTO "tiendas" VALUES(403,'50GZP','Nardos TAM',NULL);
INSERT INTO "tiendas" VALUES(405,'50GZW','8 y Garza MAF',NULL);
INSERT INTO "tiendas" VALUES(406,'50H2A','Villa Manuel MAF',NULL);
INSERT INTO "tiendas" VALUES(409,'50H6R','Madrid MAF',NULL);
INSERT INTO "tiendas" VALUES(410,'50H7X','Flamingo MAF',NULL);
INSERT INTO "tiendas" VALUES(411,'50HBI','Paseo Mendez MAF',NULL);
INSERT INTO "tiendas" VALUES(412,'50HDL','Hidalgo TAM',NULL);
INSERT INTO "tiendas" VALUES(414,'50HGM','Calle 15 TAM',NULL);
INSERT INTO "tiendas" VALUES(415,'5006I','El Galaneño MAF',NULL);
INSERT INTO "tiendas" VALUES(416,'50HHJ','Ocampo TAM',NULL);
INSERT INTO "tiendas" VALUES(417,'50HHP','Palafox TAM',NULL);
INSERT INTO "tiendas" VALUES(418,'50HII','Hombres Ilustres MAF',NULL);
INSERT INTO "tiendas" VALUES(419,'50HJB','15 Berriozabal MAF',NULL);
INSERT INTO "tiendas" VALUES(421,'50HOO','Hipodromo TAM',NULL);
INSERT INTO "tiendas" VALUES(422,'5025A','Virgilio Garza MAF',NULL);
INSERT INTO "tiendas" VALUES(423,'50HVH','Santo Nino TAM',NULL);
INSERT INTO "tiendas" VALUES(424,'50HVX','Las Americas MAF',NULL);
INSERT INTO "tiendas" VALUES(425,'50HVY','Durazno TAM',NULL);
INSERT INTO "tiendas" VALUES(426,'50HVZ','5 Ceros MAF',NULL);
INSERT INTO "tiendas" VALUES(427,'50A2A','Molino del Rey 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(428,'50HX3','Colosio II',NULL);
INSERT INTO "tiendas" VALUES(431,'50A4S','Arecas MAF',NULL);
INSERT INTO "tiendas" VALUES(432,'50AWU','Expo Fiesta MAF',NULL);
INSERT INTO "tiendas" VALUES(433,'50I2L','Gaona TAM',NULL);
INSERT INTO "tiendas" VALUES(434,'50I2V','Calle 7 TAM',NULL);
INSERT INTO "tiendas" VALUES(435,'50BAG','VoluntadyTrabajo MAM',NULL);
INSERT INTO "tiendas" VALUES(436,'50FBV','Fco I. Madero MAF',NULL);
INSERT INTO "tiendas" VALUES(437,'50HGQ','Marte R. Gomez MAF',NULL);
INSERT INTO "tiendas" VALUES(438,'50I79','Pedro Cardenas MAF',NULL);
INSERT INTO "tiendas" VALUES(439,'50IG0','Joaquin Pardave MAF',NULL);
INSERT INTO "tiendas" VALUES(440,'50IFF','Florida TAM',NULL);
INSERT INTO "tiendas" VALUES(441,'50JG1','Jesus Vega MAF',NULL);
INSERT INTO "tiendas" VALUES(442,'50JZK','Molino del Rey MAF',NULL);
INSERT INTO "tiendas" VALUES(443,'50LXP','Los Palmares MAF',NULL);
INSERT INTO "tiendas" VALUES(444,'50MJW','Misiones 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(445,'50IIL','Saltillo II TAM',NULL);
INSERT INTO "tiendas" VALUES(446,'50IJL','Campanula TAM',NULL);
INSERT INTO "tiendas" VALUES(447,'50IKH','Lopez Portillo TAM',NULL);
INSERT INTO "tiendas" VALUES(448,'50IKL','La Paz II TAM',NULL);
INSERT INTO "tiendas" VALUES(449,'50IKT','Tamatan MAF',NULL);
INSERT INTO "tiendas" VALUES(450,'50IKW','Borreguera TAM',NULL);
INSERT INTO "tiendas" VALUES(451,'50IKY','Leon TAM',NULL);
INSERT INTO "tiendas" VALUES(452,'50ILQ','Barriles TAM',NULL);
INSERT INTO "tiendas" VALUES(458,'50IMW','Volantin TAM',NULL);
INSERT INTO "tiendas" VALUES(459,'50IOX','El Eden TAM',NULL);
INSERT INTO "tiendas" VALUES(461,'50IQD','Insurgentes TAM',NULL);
INSERT INTO "tiendas" VALUES(462,'50ISP','Americo MAF',NULL);
INSERT INTO "tiendas" VALUES(463,'50ITV','Infonavit TAM',NULL);
INSERT INTO "tiendas" VALUES(465,'50QFA','Santa Cecilia MAF',NULL);
INSERT INTO "tiendas" VALUES(467,'50UGI','Gimnasio MAF',NULL);
INSERT INTO "tiendas" VALUES(468,'50UMA','Aeropuerto MAF',NULL);
INSERT INTO "tiendas" VALUES(472,'50UMN','Mundo Nuevo MAF',NULL);
INSERT INTO "tiendas" VALUES(473,'50JFT','Josefa Ortiz TAM',NULL);
INSERT INTO "tiendas" VALUES(474,'50UMZ','Mezquital MAF',NULL);
INSERT INTO "tiendas" VALUES(475,'50JJZ','Jimenez II MAF',NULL);
INSERT INTO "tiendas" VALUES(476,'50JKJ','Mainero TAM',NULL);
INSERT INTO "tiendas" VALUES(477,'50JQ5','Lomas de Guadalupe UMI',NULL);
INSERT INTO "tiendas" VALUES(478,'50JUM','Jaumave MAF',NULL);
INSERT INTO "tiendas" VALUES(481,'50JWE','Zona Centro TAM',NULL);
INSERT INTO "tiendas" VALUES(482,'50JYC','Chapultepec MAF',NULL);
INSERT INTO "tiendas" VALUES(483,'50JYD','Santuario 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(484,'50UOO','Rago MAF',NULL);
INSERT INTO "tiendas" VALUES(486,'50UOZ','Ragoz MAF',NULL);
INSERT INTO "tiendas" VALUES(487,'50WHT','Martha Rita MAF',NULL);
INSERT INTO "tiendas" VALUES(488,'50WPP','Pueblitos MAF',NULL);
INSERT INTO "tiendas" VALUES(489,'50WQX','Portes Gil  MAF',NULL);
INSERT INTO "tiendas" VALUES(490,'50XRT','Las Flores MAF',NULL);
INSERT INTO "tiendas" VALUES(491,'50YJG','12 de Marzo 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(492,'50JZT','Zaragoza 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(493,'50JZU','9 y Berriozabal MAF',NULL);
INSERT INTO "tiendas" VALUES(494,'50JZV','Oaxaca MAF',NULL);
INSERT INTO "tiendas" VALUES(495,'50JZW','San Luis MAF',NULL);
INSERT INTO "tiendas" VALUES(496,'50JZY','Sierra MAF',NULL);
INSERT INTO "tiendas" VALUES(497,'50K0A','Bravos MAF',NULL);
INSERT INTO "tiendas" VALUES(500,'50K4E','Guemez Centro MAF',NULL);
INSERT INTO "tiendas" VALUES(503,'50K6D','Los Troncones MAF',NULL);
INSERT INTO "tiendas" VALUES(504,'50K87','Villa Padilla MAF',NULL);
INSERT INTO "tiendas" VALUES(506,'50KAD','Aldama TAM',NULL);
INSERT INTO "tiendas" VALUES(507,'50KC4','Calle 9 MAF',NULL);
INSERT INTO "tiendas" VALUES(508,'50KCH','Charro TAM',NULL);
INSERT INTO "tiendas" VALUES(509,'50YJL','Misiones MAF',NULL);
INSERT INTO "tiendas" VALUES(510,'50KD1','Marina Vieja II MAF',NULL);
INSERT INTO "tiendas" VALUES(511,'50KDB','Dos Bocas TAM',NULL);
INSERT INTO "tiendas" VALUES(512,'5000G','Alameda MAF',NULL);
INSERT INTO "tiendas" VALUES(513,'50KFI','Fiscal TAM',NULL);
INSERT INTO "tiendas" VALUES(514,'50KGA','Del Valle TAM',NULL);
INSERT INTO "tiendas" VALUES(515,'50KH9','Avenida de la Industria TAM',NULL);
INSERT INTO "tiendas" VALUES(516,'50KHB','Manuel Centro TAM',NULL);
INSERT INTO "tiendas" VALUES(517,'50KHI','Avenida Hidalgo TAM',NULL);
INSERT INTO "tiendas" VALUES(518,'500OX','Brecha 119 MAF',NULL);
INSERT INTO "tiendas" VALUES(519,'50KJU','Juarez TAM',NULL);
INSERT INTO "tiendas" VALUES(520,'50KMA','Madero TAM',NULL);
INSERT INTO "tiendas" VALUES(521,'50KMT','Del Maestro MAF',NULL);
INSERT INTO "tiendas" VALUES(523,'50KSX','Sexta Avenida TAM',NULL);
INSERT INTO "tiendas" VALUES(524,'502GT','Lopez Mateos MAF',NULL);
INSERT INTO "tiendas" VALUES(525,'506BJ','Rosalinda Guerrero MAF',NULL);
INSERT INTO "tiendas" VALUES(526,'50805','6 Y Juarez MAF',NULL);
INSERT INTO "tiendas" VALUES(530,'50CHF','Chavez MAF',NULL);
INSERT INTO "tiendas" VALUES(532,'50LAO','Centralita TAM',NULL);
INSERT INTO "tiendas" VALUES(533,'50LB3','Ejido Miramar TAM',NULL);
INSERT INTO "tiendas" VALUES(535,'50LCI','Constitucion TAM',NULL);
INSERT INTO "tiendas" VALUES(537,'50LFD','Lib. Manuel TAM',NULL);
INSERT INTO "tiendas" VALUES(538,'50LFF','Llera TAM',NULL);
INSERT INTO "tiendas" VALUES(540,'50LGS','8 Leguas TAM',NULL);
INSERT INTO "tiendas" VALUES(541,'50LIG','Aguila TAM',NULL);
INSERT INTO "tiendas" VALUES(542,'50LLR','Lomas TAM',NULL);
INSERT INTO "tiendas" VALUES(543,'50LO8','Agropecuarios MAF',NULL);
INSERT INTO "tiendas" VALUES(544,'50CHV','Echeverria MAF',NULL);
INSERT INTO "tiendas" VALUES(545,'50LRH','Moscu TAM',NULL);
INSERT INTO "tiendas" VALUES(546,'50LRV','Lauro Aguirre TAM',NULL);
INSERT INTO "tiendas" VALUES(547,'50DBK','Dos de Abril MAF',NULL);
INSERT INTO "tiendas" VALUES(548,'50DNS','Cardenas MAF',NULL);
INSERT INTO "tiendas" VALUES(549,'50LUL','Luna Luna TAM',NULL);
INSERT INTO "tiendas" VALUES(550,'50DZJ','15 Y Juarez MAF',NULL);
INSERT INTO "tiendas" VALUES(551,'50EUE','Echeverria III MAF',NULL);
INSERT INTO "tiendas" VALUES(553,'50M1V','Smith TAM',NULL);
INSERT INTO "tiendas" VALUES(556,'50GHE','Echeverria IiMAF',NULL);
INSERT INTO "tiendas" VALUES(557,'50M73','Gas Manuel TMP',NULL);
INSERT INTO "tiendas" VALUES(558,'50HQW','Hidalgo MAF',NULL);
INSERT INTO "tiendas" VALUES(559,'50M82','Osa Mayor TAM',NULL);
INSERT INTO "tiendas" VALUES(560,'50MAK','Miramapolis TAM',NULL);
INSERT INTO "tiendas" VALUES(561,'50MBJ','Altamira Mercado TAM',NULL);
INSERT INTO "tiendas" VALUES(562,'50MC0','Alvaro Obregon MAF',NULL);
INSERT INTO "tiendas" VALUES(563,'50HWC','Anahuac MAF',NULL);
INSERT INTO "tiendas" VALUES(565,'50ICT','Castillo MAF',NULL);
INSERT INTO "tiendas" VALUES(566,'50MEV','Morelos TAM',NULL);
INSERT INTO "tiendas" VALUES(567,'50J3R','Anahuac Centro MAF',NULL);
INSERT INTO "tiendas" VALUES(568,'50KCS','Cardenas II MAF',NULL);
INSERT INTO "tiendas" VALUES(569,'50L32','Cosme Santos MAF',NULL);
INSERT INTO "tiendas" VALUES(570,'50L92','Soberon MAF',NULL);
INSERT INTO "tiendas" VALUES(571,'50MDW','Madero MAF',NULL);
INSERT INTO "tiendas" VALUES(572,'50Q58','Independencia MAF',NULL);
INSERT INTO "tiendas" VALUES(573,'50MRJ','Marina Vieja MAF',NULL);
INSERT INTO "tiendas" VALUES(574,'50RLT','El Realito MAF',NULL);
INSERT INTO "tiendas" VALUES(576,'50MWF','Mirador TAM',NULL);
INSERT INTO "tiendas" VALUES(577,'50SFS','Los Fresnos MAF',NULL);
INSERT INTO "tiendas" VALUES(578,'50MXY','Monte Alto TAM',NULL);
INSERT INTO "tiendas" VALUES(579,'50MY5','Tomaseno MAF',NULL);
INSERT INTO "tiendas" VALUES(580,'50V6D','Brecha 82 MAF',NULL);
INSERT INTO "tiendas" VALUES(581,'50N0O','Jaguar MAF',NULL);
INSERT INTO "tiendas" VALUES(582,'50N0P','La Isla TAM',NULL);
INSERT INTO "tiendas" VALUES(583,'50N4D','Pedro J. Mendez TAM',NULL);
INSERT INTO "tiendas" VALUES(584,'50N72','Servitrail MAF',NULL);
INSERT INTO "tiendas" VALUES(585,'50N7H','Laurel MAF',NULL);
INSERT INTO "tiendas" VALUES(586,'50N7U','Lucio Blanco TAM',NULL);
INSERT INTO "tiendas" VALUES(587,'50YME','America MAF',NULL);
INSERT INTO "tiendas" VALUES(588,'50NBQ','7 de Noviembre MAF',NULL);
INSERT INTO "tiendas" VALUES(589,'50ZZZ','Cipres MAF',NULL);
INSERT INTO "tiendas" VALUES(590,'500MJ','Diez y Victoria MAF',NULL);
INSERT INTO "tiendas" VALUES(591,'50NF7','Seis TAM',NULL);
INSERT INTO "tiendas" VALUES(594,'502BE','SAT MAF',NULL);
INSERT INTO "tiendas" VALUES(596,'50NPC','Servando Canales TAM',NULL);
INSERT INTO "tiendas" VALUES(597,'50NPD','Nuevo Padilla MAF',NULL);
INSERT INTO "tiendas" VALUES(598,'505JL','Puente Viejo MAF',NULL);
INSERT INTO "tiendas" VALUES(599,'50NS8','21 de Marzo MAF',NULL);
INSERT INTO "tiendas" VALUES(600,'50AZQ','14 Diagonal MAF',NULL);
INSERT INTO "tiendas" VALUES(602,'50BIR','Laguna Salada MAF',NULL);
INSERT INTO "tiendas" VALUES(603,'50NUD','NacionesUnidasIIMAF',NULL);
INSERT INTO "tiendas" VALUES(604,'50NVK','Pedrera TAM',NULL);
INSERT INTO "tiendas" VALUES(606,'50D98','Laguneta MAF',NULL);
INSERT INTO "tiendas" VALUES(607,'50NXH','18 de Marzo TAM',NULL);
INSERT INTO "tiendas" VALUES(608,'50NYR','Nayarit TAM',NULL);
INSERT INTO "tiendas" VALUES(609,'50FXY','8 Abasolo MAF',NULL);
INSERT INTO "tiendas" VALUES(611,'50O4H','Aquiles TAM',NULL);
INSERT INTO "tiendas" VALUES(612,'50O53','Tec Monterrey TAM',NULL);
INSERT INTO "tiendas" VALUES(616,'50OAT','Altamira Centro TAM',NULL);
INSERT INTO "tiendas" VALUES(617,'50HYA','Ayala MAF',NULL);
INSERT INTO "tiendas" VALUES(618,'50ODK','Gaviotas  TAM',NULL);
INSERT INTO "tiendas" VALUES(619,'50JZL','Centro Historico MAF',NULL);
INSERT INTO "tiendas" VALUES(620,'50KDE','Teran MAF',NULL);
INSERT INTO "tiendas" VALUES(621,'50OFO','Faja de Oro TAM',NULL);
INSERT INTO "tiendas" VALUES(622,'50OFY','Flamboyanes TAM',NULL);
INSERT INTO "tiendas" VALUES(623,'50OGO','Obregon TAM',NULL);
INSERT INTO "tiendas" VALUES(624,'50KTV','Mercado Juarez MAF',NULL);
INSERT INTO "tiendas" VALUES(626,'50OOG','Golfo TAM',NULL);
INSERT INTO "tiendas" VALUES(628,'50OOT','Ampliacion II TAM',NULL);
INSERT INTO "tiendas" VALUES(629,'50OP3','Retama TAM',NULL);
INSERT INTO "tiendas" VALUES(631,'50OPW','El Chorro TAM',NULL);
INSERT INTO "tiendas" VALUES(635,'50OSD','16 Sierra deCasasMAF',NULL);
INSERT INTO "tiendas" VALUES(636,'50NAQ','Laguna Jasso MAF',NULL);
INSERT INTO "tiendas" VALUES(637,'50NKV','20 y Gonzalez MAF',NULL);
INSERT INTO "tiendas" VALUES(638,'50OUC','Tercera Avenida TAM',NULL);
INSERT INTO "tiendas" VALUES(639,'50OUK','Adelitas MAF',NULL);
INSERT INTO "tiendas" VALUES(640,'50OUW','La Escondida MAF',NULL);
INSERT INTO "tiendas" VALUES(643,'50P02','Loma Prieta MAF',NULL);
INSERT INTO "tiendas" VALUES(644,'50P0X','Arroyo Loco MAF',NULL);
INSERT INTO "tiendas" VALUES(645,'50OTU','Triangulo MAF',NULL);
INSERT INTO "tiendas" VALUES(646,'50PA0','32 Y Matamoros MAF',NULL);
INSERT INTO "tiendas" VALUES(647,'50PAY','Plan de Ayutla MAF',NULL);
INSERT INTO "tiendas" VALUES(648,'50PD1','Jaumave 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(650,'50PHB','Brownsville TAM',NULL);
INSERT INTO "tiendas" VALUES(651,'50PHW','Pachuca TAM',NULL);
INSERT INTO "tiendas" VALUES(653,'50SGZ','Seguro Social MAF',NULL);
INSERT INTO "tiendas" VALUES(654,'50POM','1o. de Mayo TAM',NULL);
INSERT INTO "tiendas" VALUES(655,'50PTB','Uni. Poniente TAM',NULL);
INSERT INTO "tiendas" VALUES(657,'50PV1','Jose Maria TAM',NULL);
INSERT INTO "tiendas" VALUES(658,'50PXQ','Monteverde TAM',NULL);
INSERT INTO "tiendas" VALUES(661,'50UCA','San Francisco MAF',NULL);
INSERT INTO "tiendas" VALUES(663,'50UGZ','Gonzalez MAF',NULL);
INSERT INTO "tiendas" VALUES(665,'50UOA','Aguila MAF',NULL);
INSERT INTO "tiendas" VALUES(666,'50QDS','Oma TAM',NULL);
INSERT INTO "tiendas" VALUES(667,'50QDV','Cuauhtemoc Centro TAM',NULL);
INSERT INTO "tiendas" VALUES(668,'50UOM','Morelos MAF',NULL);
INSERT INTO "tiendas" VALUES(669,'50UOV','Diagonal y 20 MAF',NULL);
INSERT INTO "tiendas" VALUES(672,'50USC','Canales MAF',NULL);
INSERT INTO "tiendas" VALUES(673,'50ZPZ','Plaza Allende MAF',NULL);
INSERT INTO "tiendas" VALUES(674,'50QLJ','Sor Juana TAM',NULL);
INSERT INTO "tiendas" VALUES(675,'50QLK','Puerto Altamira TAM',NULL);
INSERT INTO "tiendas" VALUES(676,'50QOL','17 y Juarez MAF',NULL);
INSERT INTO "tiendas" VALUES(677,'50ZYU','Zaragoza MAF',NULL);
INSERT INTO "tiendas" VALUES(678,'50QOU','Nuevo Progreso TAM',NULL);
INSERT INTO "tiendas" VALUES(679,'501DD','Bella Vista Sur',NULL);
INSERT INTO "tiendas" VALUES(681,'50QVO','Camelia TAM',NULL);
INSERT INTO "tiendas" VALUES(682,'50QVW','Colonias TAM',NULL);
INSERT INTO "tiendas" VALUES(683,'501TH','Paso Real MAF',NULL);
INSERT INTO "tiendas" VALUES(684,'50QX2','Francisco Villa TAM',NULL);
INSERT INTO "tiendas" VALUES(685,'503D1','Libramiento San Fer MAF',NULL);
INSERT INTO "tiendas" VALUES(687,'50RA5','Estacion Colonias TAM',NULL);
INSERT INTO "tiendas" VALUES(688,'50RAE','Rosales TAM',NULL);
INSERT INTO "tiendas" VALUES(689,'50RAK','Cardenas TAM',NULL);
INSERT INTO "tiendas" VALUES(692,'50RFI','Refineria TAM',NULL);
INSERT INTO "tiendas" VALUES(694,'50RGN','Alijadores TAM',NULL);
INSERT INTO "tiendas" VALUES(695,'50RIM','Miramar TAM',NULL);
INSERT INTO "tiendas" VALUES(696,'505DK','Loma Alta MAF',NULL);
INSERT INTO "tiendas" VALUES(697,'505UT','Las Yescas MAF',NULL);
INSERT INTO "tiendas" VALUES(698,'50RNV','Rumbo Nuevo MAF',NULL);
INSERT INTO "tiendas" VALUES(699,'50RRA','18 de Julio MAF',NULL);
INSERT INTO "tiendas" VALUES(700,'50RRG','Benito Juarez TAM',NULL);
INSERT INTO "tiendas" VALUES(701,'50RTV','Recreativo II TAM',NULL);
INSERT INTO "tiendas" VALUES(702,'506BY','Ignacio Allende 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(703,'50RW8','Casas Blancas 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(704,'50RXA','Mar TAM',NULL);
INSERT INTO "tiendas" VALUES(705,'50RXV','Revolucion TAM',NULL);
INSERT INTO "tiendas" VALUES(706,'506VP','Padre Mier MAF',NULL);
INSERT INTO "tiendas" VALUES(707,'50RZR','Laguna Puerta TAM',NULL);
INSERT INTO "tiendas" VALUES(708,'50S1T','Alta Vista MAF',NULL);
INSERT INTO "tiendas" VALUES(709,'50S7R','Azteca MAF',NULL);
INSERT INTO "tiendas" VALUES(711,'50SA8','12 de Septiembre MAF',NULL);
INSERT INTO "tiendas" VALUES(712,'50SAC','Salubridad MAF',NULL);
INSERT INTO "tiendas" VALUES(714,'50SBA','Sarabia TAM',NULL);
INSERT INTO "tiendas" VALUES(715,'50SDQ','Naciones Unidas MAF',NULL);
INSERT INTO "tiendas" VALUES(717,'50E7Y','Ignacio Allende MAF',NULL);
INSERT INTO "tiendas" VALUES(718,'50SFR','Honduras TAM',NULL);
INSERT INTO "tiendas" VALUES(719,'50I03','San German MAF',NULL);
INSERT INTO "tiendas" VALUES(721,'50SFV','Wisconsin TAM',NULL);
INSERT INTO "tiendas" VALUES(722,'50JZN','Moquetito MAF',NULL);
INSERT INTO "tiendas" VALUES(723,'50MWZ','Bella Vista MAF',NULL);
INSERT INTO "tiendas" VALUES(724,'50NRW','Las Norias MAF',NULL);
INSERT INTO "tiendas" VALUES(725,'50SHY','Champayan TAM',NULL);
INSERT INTO "tiendas" VALUES(726,'50SIR','Satelite TAM',NULL);
INSERT INTO "tiendas" VALUES(727,'50SIT','Central TAM',NULL);
INSERT INTO "tiendas" VALUES(728,'50SIW','Nautica TAM',NULL);
INSERT INTO "tiendas" VALUES(729,'50NXE','Ruiz Cortinez MAF',NULL);
INSERT INTO "tiendas" VALUES(730,'50QKJ','Plaza MAF',NULL);
INSERT INTO "tiendas" VALUES(731,'50QW7','Carretera San Fernando MAF',NULL);
INSERT INTO "tiendas" VALUES(732,'50SKS','Enrique Cardenas TAM',NULL);
INSERT INTO "tiendas" VALUES(733,'50R1K','Juan de la Barrera MAF',NULL);
INSERT INTO "tiendas" VALUES(736,'50SNQ','San Luisito MAF',NULL);
INSERT INTO "tiendas" VALUES(737,'50SO2','14 Carrera MAF',NULL);
INSERT INTO "tiendas" VALUES(738,'50RJO','Rancho Viejo MAF',NULL);
INSERT INTO "tiendas" VALUES(740,'50RYI','2do Centenario MAF',NULL);
INSERT INTO "tiendas" VALUES(741,'50TUU','Ruiz Cortinez II MAF',NULL);
INSERT INTO "tiendas" VALUES(742,'50SRW','Sirenas TAM',NULL);
INSERT INTO "tiendas" VALUES(744,'50SUO','Santuario MAF',NULL);
INSERT INTO "tiendas" VALUES(745,'50SVA','Los Olivos TAM',NULL);
INSERT INTO "tiendas" VALUES(746,'50XLJ','Loma Colorada MAF',NULL);
INSERT INTO "tiendas" VALUES(748,'50T0S','Campeche MAF',NULL);
INSERT INTO "tiendas" VALUES(750,'50T2X','Benito Sierra 1 MAF',NULL);
INSERT INTO "tiendas" VALUES(751,'50YNO','Pino Suarez MAF',NULL);
INSERT INTO "tiendas" VALUES(752,'50ABD','Arboledas MAF',NULL);
INSERT INTO "tiendas" VALUES(754,'50TA9','Australia TAM',NULL);
INSERT INTO "tiendas" VALUES(756,'50AXJ','Alianza MAF',NULL);
INSERT INTO "tiendas" VALUES(758,'50CRE','Central MAF',NULL);
INSERT INTO "tiendas" VALUES(761,'50TFX','Las Torres TAM',NULL);
INSERT INTO "tiendas" VALUES(762,'50TG3','Rio Blanco TAM',NULL);
INSERT INTO "tiendas" VALUES(763,'50TGU','13 Yucatan MAF',NULL);
INSERT INTO "tiendas" VALUES(764,'50TH1','Juan Pablo II MAF',NULL);
INSERT INTO "tiendas" VALUES(766,'50THR','Pescador TAM',NULL);
INSERT INTO "tiendas" VALUES(768,'50TJB','Auditorio TAM',NULL);
INSERT INTO "tiendas" VALUES(769,'50TKE','Libramiento II MAF',NULL);
INSERT INTO "tiendas" VALUES(770,'50TMC','Curva Texas TAM',NULL);
INSERT INTO "tiendas" VALUES(771,'50TMK','Oralia Guerra MAF',NULL);
INSERT INTO "tiendas" VALUES(772,'50TML','Miraltas TAM',NULL);
INSERT INTO "tiendas" VALUES(773,'50TNK','Tancol TAM',NULL);
INSERT INTO "tiendas" VALUES(774,'50TOC','Cedros TAM',NULL);
INSERT INTO "tiendas" VALUES(775,'50TPI','Unidad Modelo TAM',NULL);
INSERT INTO "tiendas" VALUES(777,'50TQP','Herradura TAM',NULL);
INSERT INTO "tiendas" VALUES(778,'50TRO','Rosalio TAM',NULL);
INSERT INTO "tiendas" VALUES(779,'50TS7','Puente Roto MAF',NULL);
INSERT INTO "tiendas" VALUES(781,'50TTI','Imperial TAM',NULL);
INSERT INTO "tiendas" VALUES(782,'50TTJ','Jalisco TAM',NULL);
INSERT INTO "tiendas" VALUES(785,'50F3C','Alhelies MAF',NULL);
INSERT INTO "tiendas" VALUES(786,'50TWQ','Tenochtitlan MAF',NULL);
INSERT INTO "tiendas" VALUES(787,'50TXP','Palmas TAM',NULL);
INSERT INTO "tiendas" VALUES(788,'50TY6','Santos Degollado TAM',NULL);
INSERT INTO "tiendas" VALUES(789,'50U0F','Movil Victoria MAF',NULL);
INSERT INTO "tiendas" VALUES(792,'50U2L','Padilla Centro MAF',NULL);
INSERT INTO "tiendas" VALUES(794,'50U6I','Plaza Covadonga MAF',NULL);
INSERT INTO "tiendas" VALUES(795,'50U7A','Amalia G MAF',NULL);
INSERT INTO "tiendas" VALUES(797,'50IDZ','Alvaro Obregon MAF',NULL);
INSERT INTO "tiendas" VALUES(798,'50MPO','Ocampo MAF',NULL);
INSERT INTO "tiendas" VALUES(800,'50UDG','Campestre MAF',NULL);
INSERT INTO "tiendas" VALUES(801,'50UDI','Universidad TAM',NULL);
INSERT INTO "tiendas" VALUES(802,'50NSF','Pumarejo MAF',NULL);
INSERT INTO "tiendas" VALUES(803,'50OEM','El Moro MAF',NULL);
INSERT INTO "tiendas" VALUES(804,'50P8O','Del Cambio MAF',NULL);
INSERT INTO "tiendas" VALUES(805,'50PMA','Primera MAF',NULL);
INSERT INTO "tiendas" VALUES(806,'50SQC','San Carlos MAF',NULL);
INSERT INTO "tiendas" VALUES(807,'50ULW','Colosio TAM',NULL);
INSERT INTO "tiendas" VALUES(808,'50SQW','Solernau MAF',NULL);
INSERT INTO "tiendas" VALUES(809,'50T5W','Washington MAF',NULL);
INSERT INTO "tiendas" VALUES(810,'50UDN','Division del Norte MAF',NULL);
INSERT INTO "tiendas" VALUES(811,'50UGO','Gobernacion MAF',NULL);
INSERT INTO "tiendas" VALUES(812,'50UNA','Unidad Nacional TAM',NULL);
INSERT INTO "tiendas" VALUES(813,'50UOJ','Jardin MAF',NULL);
INSERT INTO "tiendas" VALUES(814,'50UOL','Lauro Villar MAF',NULL);
INSERT INTO "tiendas" VALUES(815,'50UOR','Rio MAF',NULL);
INSERT INTO "tiendas" VALUES(816,'50URR','Arrese MAF',NULL);
INSERT INTO "tiendas" VALUES(817,'50UVI','Vizcaya MAF',NULL);
INSERT INTO "tiendas" VALUES(818,'50VPA','Las Palmas MAF',NULL);
INSERT INTO "tiendas" VALUES(819,'50XWF','IMSS MAF',NULL);
INSERT INTO "tiendas" VALUES(820,'507UH','Las Palmitas MAF',NULL);
INSERT INTO "tiendas" VALUES(821,'508QZ','Popular MAF',NULL);
INSERT INTO "tiendas" VALUES(822,'50AIE','Emiliano Zapata MAF',NULL);
INSERT INTO "tiendas" VALUES(823,'50AKV','Accion Civica MAF',NULL);
INSERT INTO "tiendas" VALUES(824,'50D8C','Alamo MAF',NULL);
INSERT INTO "tiendas" VALUES(825,'50UQX','Sierra Madre MAF',NULL);
INSERT INTO "tiendas" VALUES(827,'50EUV','Trevino Zapata MAF',NULL);
INSERT INTO "tiendas" VALUES(828,'50F4I','Nogalar MAF',NULL);
INSERT INTO "tiendas" VALUES(829,'50IB3','Trejo MAF',NULL);
INSERT INTO "tiendas" VALUES(831,'50KXW','Paraiso MAF',NULL);
INSERT INTO "tiendas" VALUES(832,'50UUM','Aldama Centro TAM',NULL);
INSERT INTO "tiendas" VALUES(833,'50UUV','Plaza Golfo TAM',NULL);
INSERT INTO "tiendas" VALUES(834,'50M5R','Republica De Argentina MAF',NULL);
INSERT INTO "tiendas" VALUES(835,'50UXB','Berriozabal MAF',NULL);
INSERT INTO "tiendas" VALUES(836,'50UXE','Estadio MAF',NULL);
INSERT INTO "tiendas" VALUES(837,'50MCF','Cantinflas MAF',NULL);
INSERT INTO "tiendas" VALUES(838,'50V06','Loma Chairel MAF',NULL);
INSERT INTO "tiendas" VALUES(840,'50V28','EL FARO',NULL);
INSERT INTO "tiendas" VALUES(842,'50V3Z','Vela Maria TAM',NULL);
INSERT INTO "tiendas" VALUES(843,'50MPP','Durazno MAF',NULL);
INSERT INTO "tiendas" VALUES(844,'50V7Z','Bahia TAM',NULL);
INSERT INTO "tiendas" VALUES(845,'50V8G','Mirlos MAF',NULL);
INSERT INTO "tiendas" VALUES(847,'50VDI','16 Veracruz MAF',NULL);
INSERT INTO "tiendas" VALUES(848,'50VE7','Subida Alta MAF',NULL);
INSERT INTO "tiendas" VALUES(849,'50VGY','Valle de Aguayo MAF',NULL);
INSERT INTO "tiendas" VALUES(850,'50VIA','Villas TAM',NULL);
INSERT INTO "tiendas" VALUES(851,'50VJ7','Secundaria 1 MAF',NULL);
INSERT INTO "tiendas" VALUES(852,'50VJE','Eje Vial MAF',NULL);
INSERT INTO "tiendas" VALUES(853,'50VJP','Torreon TAM',NULL);
INSERT INTO "tiendas" VALUES(855,'50VNV','20 de Noviembre TAM',NULL);
INSERT INTO "tiendas" VALUES(857,'50O0A','Oceano Pacifico Sur MAF',NULL);
INSERT INTO "tiendas" VALUES(858,'50VR7','Zapotal MAF',NULL);
INSERT INTO "tiendas" VALUES(859,'50VS6','Calle A TAM',NULL);
INSERT INTO "tiendas" VALUES(860,'50OBR','Valle Verde MAF',NULL);
INSERT INTO "tiendas" VALUES(861,'50VWI','Diaz Miron TAM',NULL);
INSERT INTO "tiendas" VALUES(862,'50OL6','El Porvenir MAF',NULL);
INSERT INTO "tiendas" VALUES(863,'50VYB','Especialidades MAF',NULL);
INSERT INTO "tiendas" VALUES(864,'50W07','Tula Centro MAF',NULL);
INSERT INTO "tiendas" VALUES(866,'50W74','Carmin TAM',NULL);
INSERT INTO "tiendas" VALUES(867,'50W7M','Colinas Del Valle MAF',NULL);
INSERT INTO "tiendas" VALUES(869,'50WAY','Alemanes TAM',NULL);
INSERT INTO "tiendas" VALUES(870,'50Q0N','Jilgueros MAF',NULL);
INSERT INTO "tiendas" VALUES(871,'50WIY','Villa Cuauhtemoc TAM',NULL);
INSERT INTO "tiendas" VALUES(872,'50SLD','Solidaridad MAF',NULL);
INSERT INTO "tiendas" VALUES(873,'50SOY','Playa Sol MAF',NULL);
INSERT INTO "tiendas" VALUES(874,'50WM4','La Salle Victoria MAF',NULL);
INSERT INTO "tiendas" VALUES(876,'50WMI','Ocho Michoacan MAF',NULL);
INSERT INTO "tiendas" VALUES(877,'50WMZ','Morelos II TAM',NULL);
INSERT INTO "tiendas" VALUES(878,'50UOG','Guerra I MAF',NULL);
INSERT INTO "tiendas" VALUES(879,'50UTR','Tarahumara MAF',NULL);
INSERT INTO "tiendas" VALUES(880,'50WPU','Libertad TAM',NULL);
INSERT INTO "tiendas" VALUES(881,'50WQN','Castaneda MAF',NULL);
INSERT INTO "tiendas" VALUES(882,'50WK3','Democracia Social MAF',NULL);
INSERT INTO "tiendas" VALUES(883,'50WSR','28 Juarez MAF',NULL);
INSERT INTO "tiendas" VALUES(884,'50WU2','Villagran MAF',NULL);
INSERT INTO "tiendas" VALUES(885,'50WU4','Jaibos MAF',NULL);
INSERT INTO "tiendas" VALUES(886,'50WXC','Canaco TAM',NULL);
INSERT INTO "tiendas" VALUES(887,'50WXF','Bateria 7 TAM',NULL);
INSERT INTO "tiendas" VALUES(889,'50WYR','Flores TAM',NULL);
INSERT INTO "tiendas" VALUES(891,'50XTF','Roberto Guerra MAF',NULL);
INSERT INTO "tiendas" VALUES(892,'50YXC','Mexico MAF',NULL);
INSERT INTO "tiendas" VALUES(893,'50XBK','Mina TAM',NULL);
INSERT INTO "tiendas" VALUES(894,'50YZT','Playa Hornos MAF',NULL);
INSERT INTO "tiendas" VALUES(895,'50XDG','1 Matamoros MAF',NULL);
INSERT INTO "tiendas" VALUES(897,'501UA','Seccion 16 MAF',NULL);
INSERT INTO "tiendas" VALUES(898,'501XK','Mariano Matamoros MAF',NULL);
INSERT INTO "tiendas" VALUES(899,'50800','Callejon 5 MAF',NULL);
INSERT INTO "tiendas" VALUES(901,'50XIQ','NacionesUnidasIIIMAF',NULL);
INSERT INTO "tiendas" VALUES(902,'50XJL','Rectoria MAF',NULL);
INSERT INTO "tiendas" VALUES(903,'50AWC','Avellano MAF',NULL);
INSERT INTO "tiendas" VALUES(904,'50AWW','Espana MAF',NULL);
INSERT INTO "tiendas" VALUES(905,'50XO5','Canada TAM',NULL);
INSERT INTO "tiendas" VALUES(906,'50XOP','Plaza TAM',NULL);
INSERT INTO "tiendas" VALUES(907,'50XPT','San Pedro TAM',NULL);
INSERT INTO "tiendas" VALUES(908,'50XQZ','Pajaritos MAF',NULL);
INSERT INTO "tiendas" VALUES(909,'50DQE','18 y Espana MAF',NULL);
INSERT INTO "tiendas" VALUES(910,'50DQG','Agapito Gonzalez MAF',NULL);
INSERT INTO "tiendas" VALUES(911,'50XTN','Necaxa TAM',NULL);
INSERT INTO "tiendas" VALUES(912,'50DQQ','El Roble MAF',NULL);
INSERT INTO "tiendas" VALUES(914,'50DQY','Mexicali MAF',NULL);
INSERT INTO "tiendas" VALUES(915,'50Y4M','Jaumave Centro MAF',NULL);
INSERT INTO "tiendas" VALUES(916,'50FD8','Carlos Salazar MAF',NULL);
INSERT INTO "tiendas" VALUES(917,'50Y5Z','Tampico TAM',NULL);
INSERT INTO "tiendas" VALUES(918,'50Y6Q','Brasil MAF',NULL);
INSERT INTO "tiendas" VALUES(920,'50Y9K','Jose Silva TAM',NULL);
INSERT INTO "tiendas" VALUES(921,'50YCR','3 Carrera MAF',NULL);
INSERT INTO "tiendas" VALUES(922,'50FVN','Valle Dorado MAF',NULL);
INSERT INTO "tiendas" VALUES(923,'50YE9','Bella Vista TAM',NULL);
INSERT INTO "tiendas" VALUES(924,'50FYT','Nafarrete MAF',NULL);
INSERT INTO "tiendas" VALUES(925,'50YHI','14 Hidalgo MAF',NULL);
INSERT INTO "tiendas" VALUES(926,'50YIT','22 Iturbide MAF',NULL);
INSERT INTO "tiendas" VALUES(927,'50YJF','Rotario MAF',NULL);
INSERT INTO "tiendas" VALUES(928,'50JYE','Villa Azteca MAF',NULL);
INSERT INTO "tiendas" VALUES(929,'50YJH','Conrado MAF',NULL);
INSERT INTO "tiendas" VALUES(930,'50YJI','Olivia MAF',NULL);
INSERT INTO "tiendas" VALUES(931,'50LPW','La Salle MAF',NULL);
INSERT INTO "tiendas" VALUES(932,'50YJN','Hospital General MAF',NULL);
INSERT INTO "tiendas" VALUES(933,'50YLO','La Loma MAF',NULL);
INSERT INTO "tiendas" VALUES(934,'50YM7','Almendros MAF',NULL);
INSERT INTO "tiendas" VALUES(935,'50LTO','Valle Alto MAF',NULL);
INSERT INTO "tiendas" VALUES(936,'50YNB','Campo Faja de Oro TAM',NULL);
INSERT INTO "tiendas" VALUES(937,'50YNE','Argentina TAM',NULL);
INSERT INTO "tiendas" VALUES(939,'50Q9L','Carmen Serdan MAF',NULL);
INSERT INTO "tiendas" VALUES(940,'50YNX','Colon MAF',NULL);
INSERT INTO "tiendas" VALUES(941,'50YOB','Arecas TAM',NULL);
INSERT INTO "tiendas" VALUES(942,'50YOK','Haiti TAM',NULL);
INSERT INTO "tiendas" VALUES(943,'50YPV','Sahop TAM',NULL);
INSERT INTO "tiendas" VALUES(944,'50YTC','TEC MAF',NULL);
INSERT INTO "tiendas" VALUES(945,'50YUO','Ficus TAM',NULL);
INSERT INTO "tiendas" VALUES(946,'50YUV','Arrecifes TAM',NULL);
INSERT INTO "tiendas" VALUES(947,'50YUX','Sauce II TAM',NULL);
INSERT INTO "tiendas" VALUES(948,'50YVY','Lopez Mateos TAM',NULL);
INSERT INTO "tiendas" VALUES(949,'50YWJ','Cascajal TAM',NULL);
INSERT INTO "tiendas" VALUES(950,'50QLC','Tlaxcala MAF',NULL);
INSERT INTO "tiendas" VALUES(951,'50YZD','Obrera TAM',NULL);
INSERT INTO "tiendas" VALUES(952,'50YZF','Otomi TAM',NULL);
INSERT INTO "tiendas" VALUES(953,'50QQM','Bagdad MAF',NULL);
INSERT INTO "tiendas" VALUES(954,'50Z3O','San Felipe 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(955,'50RUO','La Aurora MAF',NULL);
INSERT INTO "tiendas" VALUES(956,'50UOP','Puerto Rico MAF',NULL);
INSERT INTO "tiendas" VALUES(958,'50ZAX','Plaza Madero TAM',NULL);
INSERT INTO "tiendas" VALUES(959,'50ZBK','Gonzalez TAM',NULL);
INSERT INTO "tiendas" VALUES(960,'50ZDA','Calzada TAM',NULL);
INSERT INTO "tiendas" VALUES(961,'50X92','Puerto Rico 2 MAF',NULL);
INSERT INTO "tiendas" VALUES(962,'50ZGP','Guadalupe TAM',NULL);
INSERT INTO "tiendas" VALUES(963,'50ZJG','Los Mangos TAM',NULL);
INSERT INTO "tiendas" VALUES(964,'50ZMH','Guerrero II TAM',NULL);
INSERT INTO "tiendas" VALUES(965,'50XAD','PaseoResidencial MAF',NULL);
INSERT INTO "tiendas" VALUES(967,'50ZMW','Metropolitano TAM',NULL);
INSERT INTO "tiendas" VALUES(968,'50ZNL','Sinaloa TAM',NULL);
INSERT INTO "tiendas" VALUES(969,'50XER','Periferico MAF',NULL);
INSERT INTO "tiendas" VALUES(970,'50XYV','Virgo MAF',NULL);
INSERT INTO "tiendas" VALUES(971,'50ZZM','Monterrey II TAM',NULL);
INSERT INTO "tiendas" VALUES(972,'50Y52','Mediterraneo MAF',NULL);
INSERT INTO "tiendas" VALUES(973,'50IOY','Movil TAM',NULL);
INSERT INTO "tiendas" VALUES(975,'5004C','Aquiles Serdan TAM','');
INSERT INTO "tiendas" VALUES(976,'5006G','Las Puentes MAF','');
INSERT INTO "tiendas" VALUES(977,'500BP','Ebano Carretera TAM','');
INSERT INTO "tiendas" VALUES(978,'500EP','Rotarios TAM','');
INSERT INTO "tiendas" VALUES(979,'500FM','Paso del Humo TAM','');
INSERT INTO "tiendas" VALUES(980,'500H3','16 de Septiembre  TAM','');
INSERT INTO "tiendas" VALUES(981,'500HQ','Santa Maria TAM','');
INSERT INTO "tiendas" VALUES(982,'500Q5','Servando TAM','');
INSERT INTO "tiendas" VALUES(983,'500S1','Eco Grande TAM','');
INSERT INTO "tiendas" VALUES(984,'500X5','Ciudad del Maiz TAM','');
INSERT INTO "tiendas" VALUES(985,'5012J','Xico Mercado TAM','');
INSERT INTO "tiendas" VALUES(986,'501E4','Estación Cárdenas MAF','');
INSERT INTO "tiendas" VALUES(987,'501GV','Agencia Matlapa MAF','');
INSERT INTO "tiendas" VALUES(988,'501IO','Matinchild MAF','');
INSERT INTO "tiendas" VALUES(989,'501W1','Gas Jaibo TAM','');
INSERT INTO "tiendas" VALUES(990,'5022Z','El Mango TAM','');
INSERT INTO "tiendas" VALUES(991,'50264','Corregidora TAM','');
INSERT INTO "tiendas" VALUES(992,'502AO','Ejercito Nacional TMP','');
INSERT INTO "tiendas" VALUES(993,'502AS','Soto y Gama TAM','');
INSERT INTO "tiendas" VALUES(994,'502E1','Del Pino MAF','');
INSERT INTO "tiendas" VALUES(995,'502J3','Miguel Aleman TAM','');
INSERT INTO "tiendas" VALUES(996,'502RQ','Loma Bonita MAF','');
INSERT INTO "tiendas" VALUES(997,'50380','El Cafetal MAF','');
INSERT INTO "tiendas" VALUES(998,'503BF','Loma Alta TAM','');
INSERT INTO "tiendas" VALUES(999,'503HS','Aquismon TAM','');
INSERT INTO "tiendas" VALUES(1000,'505GO','Tambaca TAM','');
INSERT INTO "tiendas" VALUES(1001,'505WE','Tercer Mundo TAM','');
INSERT INTO "tiendas" VALUES(1002,'5068M','Centro Tampacan TAM','');
INSERT INTO "tiendas" VALUES(1003,'506A4','Miguel Hidalgo  TAM','');
INSERT INTO "tiendas" VALUES(1004,'506F8','Deportiva Valles TAM','');
INSERT INTO "tiendas" VALUES(1005,'506J3','San Miguel TAM','');
INSERT INTO "tiendas" VALUES(1006,'506LS','Rascon 2 MAF','');
INSERT INTO "tiendas" VALUES(1007,'506WR','Gas Cuauhtemoc TAM','');
INSERT INTO "tiendas" VALUES(1008,'506ZZ','Yucatan TAM','');
INSERT INTO "tiendas" VALUES(1009,'5073X','Mendez TAM','');
INSERT INTO "tiendas" VALUES(1010,'5077X','Tetlama TAM','');
INSERT INTO "tiendas" VALUES(1011,'507LE','GAS TAMAZUNCHALE MAF','');
INSERT INTO "tiendas" VALUES(1012,'507QF','Mexico TAM','');
INSERT INTO "tiendas" VALUES(1013,'5080M','Cruz TAM','');
INSERT INTO "tiendas" VALUES(1014,'5081M','El abra MAF','');
INSERT INTO "tiendas" VALUES(1015,'5083G','Tampacan TAM','');
INSERT INTO "tiendas" VALUES(1016,'5084Z','Veteranos TAM','');
INSERT INTO "tiendas" VALUES(1017,'5089E','Chapulhuacanito TAM','');
INSERT INTO "tiendas" VALUES(1018,'508K0','Comonfort TAM','');
INSERT INTO "tiendas" VALUES(1019,'508ZZ','Ribera TAM','');
INSERT INTO "tiendas" VALUES(1020,'50916','La Curva TAM','');
INSERT INTO "tiendas" VALUES(1021,'50947','Blvd Colosio TAM','');
INSERT INTO "tiendas" VALUES(1022,'5095M','Guillermo Prieto MAF','');
INSERT INTO "tiendas" VALUES(1023,'50993','Emiliano Zapata TAM','');
INSERT INTO "tiendas" VALUES(1024,'509DV','Luis Echeverria TAM','');
INSERT INTO "tiendas" VALUES(1025,'509Q2','Azalea MAF','');
INSERT INTO "tiendas" VALUES(1026,'509YH','Agua Buena TAM','');
INSERT INTO "tiendas" VALUES(1027,'509YS','Carretera Tamasopo TAM','');
INSERT INTO "tiendas" VALUES(1028,'50A7Z','Ganadera TAM','');
INSERT INTO "tiendas" VALUES(1029,'50AGD','Burocrata TAM','');
INSERT INTO "tiendas" VALUES(1030,'50AGE','Salazar TAM','');
INSERT INTO "tiendas" VALUES(1031,'50AGG','Xolol TAM','');
INSERT INTO "tiendas" VALUES(1032,'50AGP','San Vicente TAM','');
INSERT INTO "tiendas" VALUES(1033,'50ANI','Panuco TAM','');
INSERT INTO "tiendas" VALUES(1034,'50APO','Praderas del Rio TAM','');
INSERT INTO "tiendas" VALUES(1035,'50ARH','Tencaxapa TAM','');
INSERT INTO "tiendas" VALUES(1036,'50ARP','Larraga TAM','');
INSERT INTO "tiendas" VALUES(1037,'50BDQ','Lerdo de Tejada TAM','');
INSERT INTO "tiendas" VALUES(1038,'50BDR','Olmecas TAM','');
INSERT INTO "tiendas" VALUES(1039,'50BMT','Santa Lucia TAM','');
INSERT INTO "tiendas" VALUES(1040,'50BPR','LomasdeSantiago TAM','');
INSERT INTO "tiendas" VALUES(1041,'50C7P','Horconcitos MAF','');
INSERT INTO "tiendas" VALUES(1042,'50C7Y','Unidad Norte MAF','');
INSERT INTO "tiendas" VALUES(1043,'50CLC','EntronqueXilitla TAM','');
INSERT INTO "tiendas" VALUES(1044,'50CXO','Ozuluama Centro TAM','');
INSERT INTO "tiendas" VALUES(1045,'50D30','El Sion TAM','');
INSERT INTO "tiendas" VALUES(1046,'50D37','Tanquian Escobedo MAF','');
INSERT INTO "tiendas" VALUES(1047,'50DGC','Flores Magon TAM','');
INSERT INTO "tiendas" VALUES(1048,'50DHN','Las Aguilas TAM','');
INSERT INTO "tiendas" VALUES(1049,'50DRN','Los Cocos TAM','');
INSERT INTO "tiendas" VALUES(1050,'50DT8','El Rio TAM','');
INSERT INTO "tiendas" VALUES(1051,'50E1G','FERROCARRIL','');
INSERT INTO "tiendas" VALUES(1052,'50EEN','Rio Mante TAM','');
INSERT INTO "tiendas" VALUES(1053,'50EFO','Pedregal TAM','');
INSERT INTO "tiendas" VALUES(1054,'50EFS','Tampico Valles TAM','');
INSERT INTO "tiendas" VALUES(1055,'50EG5','Villa Tampico TAM','');
INSERT INTO "tiendas" VALUES(1056,'50EW2','Comoca MAF','');
INSERT INTO "tiendas" VALUES(1057,'50EWK','Ebano TAM','');
INSERT INTO "tiendas" VALUES(1058,'50F31','Villa Cacalilao TAM','');
INSERT INTO "tiendas" VALUES(1059,'50F4Z','La Estacion TMP','');
INSERT INTO "tiendas" VALUES(1060,'50FBM','Hospital TAM','');
INSERT INTO "tiendas" VALUES(1061,'50FCQ','Matlapa TAM','');
INSERT INTO "tiendas" VALUES(1062,'50GEC','El Consuelo TAM','');
INSERT INTO "tiendas" VALUES(1063,'50GFU','Escobedo TAM','');
INSERT INTO "tiendas" VALUES(1064,'50GG2','Nuevo Morelos TAM','');
INSERT INTO "tiendas" VALUES(1065,'50GMH','Mante TAM','');
INSERT INTO "tiendas" VALUES(1066,'50GQU','Tampamolon TAM','');
INSERT INTO "tiendas" VALUES(1067,'50GSH','Valles TAM','');
INSERT INTO "tiendas" VALUES(1068,'50GUB','Tanquian TAM','');
INSERT INTO "tiendas" VALUES(1069,'50GZU','California TAM','');
INSERT INTO "tiendas" VALUES(1070,'50H3I','Tamos TAM','');
INSERT INTO "tiendas" VALUES(1071,'50H44','Canoas MAF','');
INSERT INTO "tiendas" VALUES(1072,'50HE3','Palacio Municipal MAF','');
INSERT INTO "tiendas" VALUES(1073,'50HN6','Ciudad Ocampo TAM','');
INSERT INTO "tiendas" VALUES(1074,'50HXA','Anahuac TAM','');
INSERT INTO "tiendas" VALUES(1075,'50HXF','Providencia TAM','');
INSERT INTO "tiendas" VALUES(1076,'50IM5','Carretera Nacional TAM','');
INSERT INTO "tiendas" VALUES(1077,'50IMG','Tamuin Centro TAM','');
INSERT INTO "tiendas" VALUES(1078,'50IMH','Frontera TAM','');
INSERT INTO "tiendas" VALUES(1079,'50IMI','Auto Park Valles TAM','');
INSERT INTO "tiendas" VALUES(1080,'50IMJ','Ecocentralita TAM','');
INSERT INTO "tiendas" VALUES(1081,'50IPO','Tempoal Centro TAM','');
INSERT INTO "tiendas" VALUES(1082,'50IUD','Villavicencio TAM','');
INSERT INTO "tiendas" VALUES(1083,'50J2L','Fray Andres TAM','');
INSERT INTO "tiendas" VALUES(1084,'50J9T','La Queretana MAF','');
INSERT INTO "tiendas" VALUES(1085,'50JBU','Panuco TAM','');
INSERT INTO "tiendas" VALUES(1086,'50JCL','La Loma TAM','');
INSERT INTO "tiendas" VALUES(1087,'50JWA','Santos TAM','');
INSERT INTO "tiendas" VALUES(1088,'50JWC','El Higo TAM','');
INSERT INTO "tiendas" VALUES(1089,'50JZ9','Tamasopo TAM','');
INSERT INTO "tiendas" VALUES(1090,'50K2P','Abasolo TAM','');
INSERT INTO "tiendas" VALUES(1091,'50K35','Centro Aquismon MAF','');
INSERT INTO "tiendas" VALUES(1092,'50K58','El Carmen TAM','');
INSERT INTO "tiendas" VALUES(1093,'50K5T','Mata Redonda MAF','');
INSERT INTO "tiendas" VALUES(1094,'50K9Q','De las Rosas TAM','');
INSERT INTO "tiendas" VALUES(1095,'50KOJ','Edarsi TAM','');
INSERT INTO "tiendas" VALUES(1096,'50L5A','Aurora TAM','');
INSERT INTO "tiendas" VALUES(1097,'50L80','Calentadores MAF','');
INSERT INTO "tiendas" VALUES(1098,'50L8J','La Purisima TAM','');
INSERT INTO "tiendas" VALUES(1099,'50L9W','Plaza Tancanhuitz TAM','');
INSERT INTO "tiendas" VALUES(1100,'50LCB','General Anaya TAM','');
INSERT INTO "tiendas" VALUES(1101,'50LDJ','Pueblo Viejo TAM','');
INSERT INTO "tiendas" VALUES(1102,'50LFI','San Felipe TAM','');
INSERT INTO "tiendas" VALUES(1103,'50M0W','Tipzen MAF','');
INSERT INTO "tiendas" VALUES(1104,'50M20','Televalles MAF','');
INSERT INTO "tiendas" VALUES(1105,'50M3P','Pujal Coy MAF','');
INSERT INTO "tiendas" VALUES(1106,'50MDN','Zacatipan TAM','');
INSERT INTO "tiendas" VALUES(1107,'50MT3','21 de Abril TAM','');
INSERT INTO "tiendas" VALUES(1108,'50NFH','La Pimienta TAM','');
INSERT INTO "tiendas" VALUES(1109,'50NFI','Gas Higo TAM','');
INSERT INTO "tiendas" VALUES(1110,'50NML','Limon TAM','');
INSERT INTO "tiendas" VALUES(1111,'50NTK','Autopark Mante TAM','');
INSERT INTO "tiendas" VALUES(1112,'50NWL','Bernal TAM','');
INSERT INTO "tiendas" VALUES(1113,'50O3Y','Huasteca TMP','');
INSERT INTO "tiendas" VALUES(1114,'50O56','Independencia TAM','');
INSERT INTO "tiendas" VALUES(1115,'50O58','Caseta Panuco TAM','');
INSERT INTO "tiendas" VALUES(1116,'50O9V','Huehuetlan TAM','');
INSERT INTO "tiendas" VALUES(1117,'50OMU','Moralillo II TAM','');
INSERT INTO "tiendas" VALUES(1118,'50OOM','Moralillo TAM','');
INSERT INTO "tiendas" VALUES(1119,'50OPF','Tampico Alto II TAM','');
INSERT INTO "tiendas" VALUES(1120,'50OR1','Avance  TAM','');
INSERT INTO "tiendas" VALUES(1121,'50OR5','El Martillo TAM','');
INSERT INTO "tiendas" VALUES(1122,'50OS4','05 de Febrero TAM','');
INSERT INTO "tiendas" VALUES(1123,'50OZL','Ozuluama II TAM','');
INSERT INTO "tiendas" VALUES(1124,'50OZU','Ozuluama TAM','');
INSERT INTO "tiendas" VALUES(1125,'50PGW','Paniagua TAM','');
INSERT INTO "tiendas" VALUES(1126,'50PJW','Pujal TAM','');
INSERT INTO "tiendas" VALUES(1127,'50PUC','Panuco II TAM','');
INSERT INTO "tiendas" VALUES(1128,'50PZ5','Huichihuayan MAF','');
INSERT INTO "tiendas" VALUES(1129,'50Q0M','Condueños MAF','');
INSERT INTO "tiendas" VALUES(1130,'50Q27','Buenos Aires TAM','');
INSERT INTO "tiendas" VALUES(1131,'50Q7H','Naranjo Centro TAM','');
INSERT INTO "tiendas" VALUES(1132,'50QFG','Panuco IV TAM','');
INSERT INTO "tiendas" VALUES(1133,'50QFS','Tres Filos TAM','');
INSERT INTO "tiendas" VALUES(1134,'50QV1','Villa Huasteca TAM','');
INSERT INTO "tiendas" VALUES(1135,'50R68','Acuario TAM','');
INSERT INTO "tiendas" VALUES(1136,'50RD4','Aviacion Mante TAM','');
INSERT INTO "tiendas" VALUES(1137,'50RF7','San Martin TAM','');
INSERT INTO "tiendas" VALUES(1138,'50RG8','Carretera Del Maiz TAM','');
INSERT INTO "tiendas" VALUES(1139,'50S9S','MOTOLINIA','');
INSERT INTO "tiendas" VALUES(1140,'50SAQ','Sabalo TAM','');
INSERT INTO "tiendas" VALUES(1141,'50SFL','Doracely TAM','');
INSERT INTO "tiendas" VALUES(1142,'50SFT','Linares TAM','');
INSERT INTO "tiendas" VALUES(1143,'50SM7','Carretera Mante TAM','');
INSERT INTO "tiendas" VALUES(1144,'50SNN','Congreg Hidalgo TAM','');
INSERT INTO "tiendas" VALUES(1145,'50SQ7','Valles Tampico MAF','');
INSERT INTO "tiendas" VALUES(1146,'50ST3','Boulevard Tamuin TAM','');
INSERT INTO "tiendas" VALUES(1147,'50T0H','Zaragoza TAM','');
INSERT INTO "tiendas" VALUES(1148,'50T2U','Punto Novel MAF','');
INSERT INTO "tiendas" VALUES(1149,'50T91','Tec Tamazunchale MAF','');
INSERT INTO "tiendas" VALUES(1150,'50TBI','Tampaon TAM','');
INSERT INTO "tiendas" VALUES(1151,'50TDF','Xalapa TAM','');
INSERT INTO "tiendas" VALUES(1152,'50TEJ','Glorieta TAM','');
INSERT INTO "tiendas" VALUES(1153,'50TES','Xilitla TAM','');
INSERT INTO "tiendas" VALUES(1154,'50THJ','Centro Tamanzuchale TAM','');
INSERT INTO "tiendas" VALUES(1155,'50TI2','Llave TAM','');
INSERT INTO "tiendas" VALUES(1156,'50TPY','Tempoal TAM','');
INSERT INTO "tiendas" VALUES(1157,'50TT2','Mercado Panuco TAM','');
INSERT INTO "tiendas" VALUES(1158,'50TTN','Crucero TAM','');
INSERT INTO "tiendas" VALUES(1159,'50TUI','Tamuin TAM','');
INSERT INTO "tiendas" VALUES(1160,'50U1U','Coxcatlan TAM','');
INSERT INTO "tiendas" VALUES(1161,'50U2F','Galeana Valles MAF','');
INSERT INTO "tiendas" VALUES(1162,'50U5K','Mante Platino MAF','');
INSERT INTO "tiendas" VALUES(1163,'50U9L','Mante Centro TAM','');
INSERT INTO "tiendas" VALUES(1164,'50UCT','Panuco III TAM','');
INSERT INTO "tiendas" VALUES(1165,'50UR4','Nicolas Moreno TAM','');
INSERT INTO "tiendas" VALUES(1166,'50UT9','Vista Hermosa TAM','');
INSERT INTO "tiendas" VALUES(1167,'50V1D','Chicoasen MAF','');
INSERT INTO "tiendas" VALUES(1168,'50V37','Antiguo Morelos TAM','');
INSERT INTO "tiendas" VALUES(1169,'50VBC','Valles Centro TAM','');
INSERT INTO "tiendas" VALUES(1170,'50VMJ','Olivo TAM','');
INSERT INTO "tiendas" VALUES(1171,'50VOG','Ebano Centro TAM','');
INSERT INTO "tiendas" VALUES(1172,'50W6J','Ahuacatlan TAM','');
INSERT INTO "tiendas" VALUES(1173,'50W7N','La Esperanza MAF','');
INSERT INTO "tiendas" VALUES(1174,'50WM8','La Gloria TAM','');
INSERT INTO "tiendas" VALUES(1175,'50WXT','Aire TAM','');
INSERT INTO "tiendas" VALUES(1176,'50X0E','Gas Tempoal TAM','');
INSERT INTO "tiendas" VALUES(1177,'50XDY','Iturbide TAM','');
INSERT INTO "tiendas" VALUES(1178,'50XIJ','Xico TAM','');
INSERT INTO "tiendas" VALUES(1179,'50XXC','Axtla TAM','');
INSERT INTO "tiendas" VALUES(1180,'50Y75','Palmira MAF','');
INSERT INTO "tiendas" VALUES(1181,'50YNI','Apolo TAM','');
INSERT INTO "tiendas" VALUES(1182,'50Z98','Del Campo TAM','');
INSERT INTO "tiendas" VALUES(1183,'50ZMJ','Malecon TAM','');
INSERT INTO "tiendas" VALUES(1184,'50OW7','Turistico 2 MAF','');
CREATE TABLE usuarios (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        usuario TEXT UNIQUE NOT NULL,
        nombre TEXT,
        password TEXT NOT NULL,
        rol TEXT NOT NULL
    );
INSERT INTO "usuarios" VALUES(1,'','','blugzUBW','lider');
INSERT INTO "usuarios" VALUES(2,'alejandro.barreda@oxxo.com','Alejandro Barreda','Netbios85*2','admin');
INSERT INTO "usuarios" VALUES(3,'rosa.ramirezoxxo.com','Rosa Martha Ramirez','Netbios85*1','admin');
INSERT INTO "usuarios" VALUES(5,'alonso.bautista@oxxo.com','Alonso Bautista Del Angel','V9goSrbs','asesor');
INSERT INTO "usuarios" VALUES(6,'angelica.lee@oxxo.com','Angelica Lee Zapata','hgNHGws0','asesor');
INSERT INTO "usuarios" VALUES(7,'maria.marino@oxxo.com','Maria del Rosario Marino Alvizo','p7Y6BIjM','asesor');
INSERT INTO "usuarios" VALUES(8,'isaac.hernandez@oxxo.com','Isaac Hernandez Martinez','FO9TSjLG','asesor');
INSERT INTO "usuarios" VALUES(9,'miguel.rubiocruz@oxxo.com','Miguel Angel Rubio Cruz','rtVhWGLN','asesor');
INSERT INTO "usuarios" VALUES(10,'vicente.blasco@oxxo.com','Vicente Manuel Blasco Flores','Yq8NTXhb','asesor');
INSERT INTO "usuarios" VALUES(11,'jose.nunez@oxxo.com','Jose Alberto Nunez Perez','ZNVxYdd3','asesor');
INSERT INTO "usuarios" VALUES(12,'jorge.camargo@oxxo.com','Miguel Angel Rubio Cruz','yf70Z7PE','asesor');
INSERT INTO "usuarios" VALUES(14,'enrique.gil@oxxo.com','Enrique Gil','Netbios85*','admin');
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('usuarios',226);
INSERT INTO "sqlite_sequence" VALUES('tiendas',1184);
COMMIT;
